---
title: "PV2003 Replication"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r,message = FALSE,warning = FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
```

##Custom Functions

```{r}
#Easy standardisation function
z <- function(x,remove.outliers = FALSE,winsorise = FALSE){
	out <- (x - mean(x,na.rm = TRUE))/sd(x,na.rm = TRUE)
	if (remove.outliers == TRUE){
	  out <- ifelse(out >3,NA,ifelse(out < -3,NA,out))
	}
	if (winsorise == TRUE){
	  out <- ifelse(out > 3,3,ifelse(out < -3,-3,out))
	}
	return(out)
}

#Easy descriptive statistics function
descriptives <- function(data,variables){
	output <- data.frame("variable"=variables,"N"=NA,"min"=NA,"max"=NA,"mean"=NA,"sd"=NA)
	d <- as.data.frame(data[variables])
	for (v in 1:NROW(variables)){
		output[v,"N"] <- sum(!is.na(d[v]))
		output[v,"min"] <- min(d[,v],na.rm=TRUE)
		output[v,"max"] <- max(d[,v],na.rm=TRUE)
		output[v,"mean"] <- mean(d[,v],na.rm=TRUE)
		output[v,"sd"] <- sd(d[,v],na.rm=TRUE)
	}
	print(output)
	return(data)
}

se <- function(x,na.rm = TRUE){
		out <- sd(x,na.rm = na.rm)/sqrt(length(x))
		return(out)
}
```

##Load Data

###Participant Level Data
```{r}
##Select ratings of male faces on sexual dimorphism
data1 <- read.csv("OCMATE_facepref.csv",stringsAsFactors = FALSE) %>%
	filter(block == 1) %>%
	filter(manip == "sexdim") %>%
	filter(face_sex == "men") %>%
	select(oc_id,age,sexpref,context,manip,face_id,rating)

##Select age at first test session.
data.l2 <- group_by(data1,oc_id) %>%
	filter(row_number() == 1) %>%
	select(oc_id,age,sexpref)

data2 <- read.csv("OCMATE Block 1 Week 1 Attractiveness Ratings.csv",stringsAsFactors = FALSE) %>%
	mutate(	oc_id = as.numeric(substr(trial,4,nchar(trial)))) %>%
	group_by(oc_id) %>%
	summarise(rater.attr = mean(dv)) %>%
	left_join(data.l2,by = "oc_id") %>%
  descriptives(c("age","rater.attr")) %>%
	mutate(age = z(age),
			rater.attr = z(rater.attr))
```

###Rating Level Data
```{r}
data.l1 <- data1 %>%
	select(oc_id,manip,face_id,context,rating) %>%
	mutate(context = recode(context,"LT" = .5,"ST" = -.5),
	       rating = recode(rating,`0` = -3.5,`1` = -2.5,`2` = -1.5,`3` = -.5,`4` = .5,`5` = 1.5,`6` = 2.5,`7` = 3.5))
```

###Join Datasets
```{r}
analysis.data <- left_join(data.l1,data2,by = "oc_id")
```

##Linear Mixed Effect Model
```{r}
model <- lmer(rating ~ context*rater.attr +
						(1 + context | oc_id) +
						(1 + context*rater.attr |face_id),analysis.data)

summary(model)
```
```{r,echo = FALSE,eval = FALSE}
format_lmer <- function(.model,file,variable = NA, label = NA,reorder = NA){
	s <- suppressWarnings(summary(.model))
	fixed <- s$coefficients
	random <- s$varcor
	fixed <- cbind(format(round(fixed[,1:3],digits = 2),nsmall = 2),format(round(fixed[,4],2),nsmall = 2),format(round(fixed[,5],3),nsmall = 2))

colnames(fixed) <- colnames(s$coefficients)
	
	sig <- function(x){
		o <- ""
		if(x < .05){o <- "*"}
		if(x < .01){o <- "**"}
		if(x < .001){o <- "***"}
		out <- paste(x,o,sep="")
	}
	
	fixed[,5] <- unlist(lapply(as.list(fixed[,5]),sig))
	
	dec <- function(x){
		temp <- substr(trimws(x),1,2)
		if(temp == "-0"){x <- gsub("-0."," -.",x)}
		if(temp == "0."){x <- gsub("0\\."," .",x)}
		if(grepl("000",x)){x <- "<.001***"}
		x
	}
	
	fixed[,1] <- unlist(lapply(as.list(fixed[,1]),dec))
	fixed[,2] <- unlist(lapply(as.list(fixed[,2]),dec))
	fixed[,3] <- unlist(lapply(as.list(fixed[,3]),dec))
	fixed[,4] <- unlist(lapply(as.list(fixed[,4]),dec))
	fixed[,5] <- unlist(lapply(as.list(fixed[,5]),dec))
	
	fixed[,1] <- paste(trimws(fixed[,1])," (",trimws(fixed[,2]),")",sep="")
	fixed[,4] <- paste(trimws(fixed[,4])," (",trimws(fixed[,3]),")",sep="")
	fixed <- fixed[,c(1,4,5)]
		
	fixed_names <- c("Estimate (Std Error)","t-value (approx df.)","p-value")
	colnames(fixed) <- fixed_names
	
	#output <- rbind(c("FIXED EFFECTS","",""),fixed_names,fixed)
	output <- fixed
	row_names <- rownames(fixed)
	
	rn <- function(x){
		x <- gsub(":"," * ",x)
		x <- gsub("\\(Intercept\\)","Intercept",x)
		suppressWarnings(if (!is.na(label)){
			for (v in 1:NROW(variable)){
				x <- gsub(variable[v],label[v],x)
			}
		})
		x
	}

	row_names <- rn(row_names)
	rownames(output) <- c(row_names)
	
	if (!anyNA(reorder)){
		output <- output[reorder,]
	}
	
	write.csv(output,file)
	
	return(output)
	#Reorder Traits
	#UNFINISHED - RANDOM EFFECTS
}

format_lmer(model,"PV2003_results.csv",variable = c("context","rater.attr"),label = c("Relationship Context","Rater Attractiveness"))
```

##Plot Data
```{r}
plot.data <- analysis.data %>%
	group_by(oc_id) %>%
	summarise(	rater.attr = mean(rater.attr),
				se.rating = se(rating,na.rm = TRUE),
				rating = mean(rating,na.rm = TRUE)
				) %>%
	mutate(ymax = rating + se.rating,
			ymin = rating - se.rating)

ggplot(analysis.data,aes(x = rater.attr,y = rating)) +
	geom_smooth(aes(colour = as.factor(context),group = as.factor(context)),method = "lm") +
	geom_pointrange(data = plot.data,aes(ymax = ymax, ymin = ymin),size = .1,alpha = .25) +
	xlab("Other-Rated Attractiveness") +
	ylab("Mean Preference for Masculinity (± S.E.)") +
  scale_colour_discrete(name = "Relationship Context",labels = c("Short-Term","Long-Term"),h.start = 75) +
  theme_classic()

#ggsave("Figure 1.png")
```